const fs=require('fs');
const crypto=require('crypto');
const DIR='_import_koc_laforin';
const PRODUCT_CODE='L01248';
const PRODUCT_NAME='Laforin stick - Hộp 20 gói 15ml (mix vị)';
const CAMPAIGN_CODE='LAFORIN_STICK';
const CAMPAIGN_NAME='KOC Laforin Stick';
function parseCsv(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const ch=text[i],nx=text[i+1];if(q){if(ch==='"'&&nx==='"'){cell+='"';i++;}else if(ch==='"'){q=false;}else cell+=ch;}else{if(ch==='"')q=true;else if(ch===','){row.push(cell);cell='';}else if(ch==='\n'){row.push(cell);rows.push(row);row=[];cell='';}else if(ch!=='\r')cell+=ch;}} if(cell.length||row.length){row.push(cell);rows.push(row);} return rows;}
const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
const isBlank=s=>!clean(s);
function normalizeLink(v){let s=clean(v); if(!s) return ''; if(/^@/.test(s)) return 'https://www.tiktok.com/'+s; if(!/^https?:\/\//i.test(s)){ s=s.replace(/^\/+/, ''); if(!s.includes('.') && !s.includes('/')) return 'https://www.tiktok.com/@'+s.replace(/^@/,''); if(!s.startsWith('www.')) return 'https://www.tiktok.com/@'+s.replace(/^@/,''); return 'https://'+s; } return s;}
function linkKey(v){let s=normalizeLink(v).toLowerCase(); try{const u=new URL(s); s=u.origin+u.pathname;}catch{} return s.replace(/\/$/,'');}
function num(v){let s=clean(v).replace(/[.\s]/g,'').replace(/,/g,''); if(!s) return 0; const m=s.match(/-?\d+(\.\d+)?/); return m?Number(m[0]):0;}
function money(v){let s=clean(v).toLowerCase(); if(!s) return 0; let n=num(s); if(/k\b|nghìn|ngan/.test(s)) n*=1000; if(/tr|triệu|trieu/.test(s)) n*=1000000; return n||0;}
function parseDate(v){let s=clean(v); if(!s) return ''; let m=s.match(/^(\d{1,2})[\/.-](\d{1,2})(?:[\/.-](\d{2,4}))?$/); if(!m) return s; let d=+m[1], mo=+m[2], y=m[3]?+m[3]:2026; if(y<100)y+=2000; if(d<1||d>31||mo<1||mo>12)return s; return `${y}-${String(mo).padStart(2,'0')}-${String(d).padStart(2,'0')}`;}
function mapStatus(raw, row={}){const s=clean(raw).toLowerCase(); const sample=clean(row.sample).toLowerCase(); const video=clean(row.videoLink); const gmv=num(row.gmv); const sold=num(row.sold); if(gmv>0||sold>0) return 'Có đơn'; if(video||num(row.videoAir)>0) return 'Đã air'; if(/duyệt/.test(s)) return 'Đã duyệt demo'; if(/gửi demo|gui demo/.test(s)) return 'Đã gửi demo'; if(/cần sửa|can sua/.test(s)) return 'Cần sửa demo'; if(/đã gửi|da gui|gửi hàng|gui hang/.test(sample)) return 'Đã gửi sản phẩm'; if(/không hợp|ko hợp|khong hop/.test(s)) return 'Không hợp tác'; if(/hợp tác|hop tac|đã thanh toán|da thanh toan/.test(s)) return 'Đồng ý hợp tác'; if(/ko phản|không phản|cho phản|chờ phản|phan hoi/.test(s)) return 'Chờ phản hồi'; if(/đã liên hệ|da lien he/.test(s)) return 'Đã liên hệ'; return raw?clean(raw):'Đã liên hệ';}
function sourceId(obj){return crypto.createHash('sha1').update([obj.sheet,obj.name,obj.link,obj.date,obj.rawStatus,obj.videoLink].map(x=>clean(x)).join('|')).digest('hex').slice(0,16);}
function fromDanhSach(){const rows=parseCsv(fs.readFileSync(`${DIR}/danh_sach_koc.csv`,'utf8')).slice(1); return rows.map((r,i)=>{const name=clean(r[0]); if(!name) return null; const link=normalizeLink(r[1]); if(!name && !link) return null; return {sheet:'Danh sách KOC',idx:i+2,date:'',name,link,follower:r[2],contact:r[3],gmv:'',sold:'',cost:r[4]||r[17],sample:r[8],sampleMethod:r[9],rawStatus:r[5],owner:r[6],product:r[7]||'Laforin stick',videoCommit:r[8],videoAir:'',dealDate:r[10],deadlineDemo:r[11],demo:r[12],feedback:r[13],videoLink:r[14],airDate:r[15],adsCode:r[16],view:r[18],like:r[19],comment:r[20],save:r[21],share:r[22],note:''}; }).filter(Boolean);}
function fromStd(file,sheet){const rows=parseCsv(fs.readFileSync(`${DIR}/${file}`,'utf8')).slice(1); return rows.map((r,i)=>{const name=clean(r[1]); if(!name) return null; const link=normalizeLink(r[2]); return {sheet,idx:i+2,date:r[0],name,link,follower:r[3],contact:r[4],gmv:r[5],sold:r[6],shipInfo:r[7],tracking:r[8],cost:r[9],sample:r[10],sampleMethod:r[11],rawStatus:r[12],product:r[13]||'Laforin stick',videoCommit:r[14],videoAir:r[15],dealDate:r[16],videoLink:r[17],airDate:r[18],owner:r[19],adsCode:r[20],note:''}; }).filter(Boolean);}
function buildImportRows(){let all=[...fromDanhSach(),...fromStd('koc_hop_tac.csv','KOC Hợp tác'),...fromStd('koc_free_cast.csv','KOC free cast')]; all=all.filter(r=>/laforin|^$/i.test(clean(r.product)) || r.sheet==='KOC free cast'); all.forEach(r=>{r.importSourceId=sourceId(r);}); return all;}
function nextCode(existing){const used=new Set(existing.map(r=>r.maKoc).filter(Boolean)); let i=1; while(used.has('KOC'+String(i).padStart(3,'0'))) i++; return 'KOC'+String(i).padStart(3,'0');}
const html=fs.readFileSync('index.html','utf8');
const url=(html.match(/const SUPA_URL\s*=\s*'([^']+)'/)||[])[1];
const key=(html.match(/const SUPA_KEY\s*=\s*'([^']+)'/)||[])[1];
async function rpc(fn,body){const res=await fetch(`${url}/rest/v1/rpc/${fn}`,{method:'POST',headers:{apikey:key,authorization:`Bearer ${key}`,'content-type':'application/json'},body:JSON.stringify(body||{})}); const text=await res.text(); if(!res.ok)throw new Error(`${fn} ${res.status} ${text}`); return text?JSON.parse(text):null;}
async function main(){const write=process.argv.includes('--write'); const rows=buildImportRows(); const kv=await rpc('kv_get_all',{}); const get=k=>(kv.find(r=>r.key===k)?.payload)||[]; let master=Array.isArray(get('mkt_sale_koc_master'))?get('mkt_sale_koc_master'):[]; let prod=Array.isArray(get('mkt_sale_koc_product_campaigns'))?get('mkt_sale_koc_product_campaigns'):[]; let pt=Array.isArray(get('mkt_sale_koc_ptlist'))?get('mkt_sale_koc_ptlist'):['Hạ','Ngân','Hồng','Nghi','Chị Hiền','Agency'];
fs.writeFileSync(`${DIR}/backup_before_import.json`, JSON.stringify({at:new Date().toISOString(),master,prod,pt},null,2));
const masterByKey=new Map(); for(const m of master){const key=linkKey(m.socialLink)||clean(m.ten).toLowerCase(); if(key) masterByKey.set(key,m);} let addedMaster=0, updatedMaster=0;
const importToMaster=new Map();
for(const r of rows){const key=linkKey(r.link)||clean(r.name).toLowerCase(); let m=masterByKey.get(key); if(!m){m={id:Date.now()+Math.random()+addedMaster,maKoc:nextCode(master),ten:r.name,socialLink:r.link,follower:num(r.follower),lienHe:clean(r.contact),nenTangChinh:r.link?'TikTok':'',nhomND:'',phuTrach:clean(r.owner),ghiChu:`Import ${r.sheet}`}; master.push(m); masterByKey.set(key,m); addedMaster++;} else {let changed=false; if(!m.ten&&r.name){m.ten=r.name;changed=true;} if(!m.socialLink&&r.link){m.socialLink=r.link;changed=true;} if((!m.follower||m.follower===0)&&num(r.follower)){m.follower=num(r.follower);changed=true;} if(!m.lienHe&&clean(r.contact)){m.lienHe=clean(r.contact);changed=true;} if(!m.phuTrach&&clean(r.owner)){m.phuTrach=clean(r.owner);changed=true;} if(changed)updatedMaster++;} importToMaster.set(r.importSourceId,m); if(r.owner && !pt.includes(clean(r.owner))) pt.push(clean(r.owner));}
const prodBySource=new Map(prod.filter(p=>p.importSourceId).map(p=>[p.importSourceId,p])); let addedProd=0, updatedProd=0;
for(const r of rows){const m=importToMaster.get(r.importSourceId); const item={id:prodBySource.get(r.importSourceId)?.id||Date.now()+Math.random()+addedProd,importSourceId:r.importSourceId,sourceSheet:r.sheet,sourceRow:r.idx,maKoc:m?.maKoc||'',tenKoc:m?.ten||r.name,maCd:CAMPAIGN_CODE,tenCd:CAMPAIGN_NAME,maSp:PRODUCT_CODE,tenSp:PRODUCT_NAME,trangThai:mapStatus(r.rawStatus,r),chiPhiBooking:money(r.cost),hoaHongPct:0,sanPhamGui:clean(r.sample),ngayGuiSP:parseDate(r.date),hinhThucNhanSP:clean(r.sampleMethod),deadlineDemo:parseDate(r.deadlineDemo),demo:clean(r.demo),feedbackDemo:clean(r.feedback),videoCamKet:num(r.videoCommit),videoCanDuyet:0,videoDaDuyet:0,videoDaAir:num(r.videoAir),linkVideo:normalizeLink(r.videoLink),ngayAir:parseDate(r.airDate),maChayAds:clean(r.adsCode),view:num(r.view),tim:num(r.like),cmt:num(r.comment),luu:num(r.save),share:num(r.share),gmv:num(r.gmv),soMonBanRa:num(r.sold),ghiChu:[`Import ${r.sheet} dòng ${r.idx}`, r.dealDate?`Ngày chốt: ${clean(r.dealDate)}`:'', r.shipInfo?`Nhận hàng: ${clean(r.shipInfo)}`:'', r.tracking?`Mã vận đơn: ${clean(r.tracking)}`:'', r.rawStatus?`Trạng thái sheet: ${clean(r.rawStatus)}`:''].filter(Boolean).join(' | ')}; const existing=prodBySource.get(r.importSourceId); if(existing){Object.assign(existing,item); updatedProd++;} else {prod.push(item); prodBySource.set(r.importSourceId,item); addedProd++;}}
const summary={inputRows:rows.length,addedMaster,updatedMaster,totalMaster:master.length,addedProductRows:addedProd,updatedProductRows:updatedProd,totalProductRows:prod.length,bySheet:rows.reduce((a,r)=>{a[r.sheet]=(a[r.sheet]||0)+1;return a;},{}),write}; console.log(JSON.stringify(summary,null,2));
if(write){await rpc('kv_set',{p_key:'mkt_sale_koc_master',p_payload:master,p_user_id:null}); await rpc('kv_set',{p_key:'mkt_sale_koc_product_campaigns',p_payload:prod,p_user_id:null}); await rpc('kv_set',{p_key:'mkt_sale_koc_data',p_payload:prod,p_user_id:null}); await rpc('kv_set',{p_key:'mkt_sale_koc_ptlist',p_payload:pt,p_user_id:null}); console.log('WRITE_OK');}
}
main().catch(e=>{console.error(e.stack||e.message); process.exit(1);});
